module main

import nats

fn main() {
	// Connect to NATS server
	mut nc := nats.connect('nats://127.0.0.1:4222')!
	defer { nc.close() }

	// Subscribe to 'service.echo' subject to act as a responder
	nc.subscribe('service.echo')!
	nc.flush()!
	println('listening on service.echo')

	// Infinite loop: wait for requests and send responses
	for {
		// next_msg() blocks and waits for an incoming request
		msg := nc.next_msg()!
		println('received: ${msg.text()}')

		// Check if this message has a reply subject (i.e., it's a request, not just a message)
		// reply is auto-generated by the request() caller and is unique per request
		if msg.reply != '' {
			// Echo the message back by publishing to the reply subject
			nc.publish_string(msg.reply, msg.text())!
			nc.flush()!
		}
	}
}
